Repository coreruleset/go-ftw, pull requests merged in 2022-09, with the labels that each got.

#65 docs: Update README will all new features
  README.md
Labels: documentation

#76 fix: remove RTT tracking from client/transport in favor of direct tra…
  ftwhttp/client.go
  ftwhttp/client_test.go
  ftwhttp/connection.go
  ftwhttp/rtt.go
  ftwhttp/types.go
  runner/run.go
Labels: bug, enhancement

#84 fix: Close net.Conn before setting up a new one
  ftwhttp/client.go
Labels: bug
